# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designer_files/baocao_thongke.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_filter = QtWidgets.QHBoxLayout()
        self.layout_filter.setObjectName("layout_filter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.layout_filter.addWidget(self.label)
        self.date_tu_ngay = QtWidgets.QDateEdit(self.centralwidget)
        self.date_tu_ngay.setCalendarPopup(True)
        self.date_tu_ngay.setObjectName("date_tu_ngay")
        self.layout_filter.addWidget(self.date_tu_ngay)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.layout_filter.addWidget(self.label_2)
        self.date_den_ngay = QtWidgets.QDateEdit(self.centralwidget)
        self.date_den_ngay.setCalendarPopup(True)
        self.date_den_ngay.setObjectName("date_den_ngay")
        self.layout_filter.addWidget(self.date_den_ngay)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_filter.addItem(spacerItem)
        self.verticalLayout.addLayout(self.layout_filter)
        self.layout_buttons = QtWidgets.QHBoxLayout()
        self.layout_buttons.setObjectName("layout_buttons")
        self.btn_doanh_thu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_doanh_thu.setObjectName("btn_doanh_thu")
        self.layout_buttons.addWidget(self.btn_doanh_thu)
        self.btn_dich_vu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dich_vu.setObjectName("btn_dich_vu")
        self.layout_buttons.addWidget(self.btn_dich_vu)
        self.btn_nhan_vien = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nhan_vien.setObjectName("btn_nhan_vien")
        self.layout_buttons.addWidget(self.btn_nhan_vien)
        self.verticalLayout.addLayout(self.layout_buttons)
        self.table_report = QtWidgets.QTableWidget(self.centralwidget)
        self.table_report.setAlternatingRowColors(True)
        self.table_report.setObjectName("table_report")
        self.table_report.setColumnCount(0)
        self.table_report.setRowCount(0)
        self.verticalLayout.addWidget(self.table_report)
        self.layout_summary = QtWidgets.QHBoxLayout()
        self.layout_summary.setObjectName("layout_summary")
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_summary.addItem(spacerItem1)
        self.lbl_summary = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_summary.setFont(font)
        self.lbl_summary.setObjectName("lbl_summary")
        self.layout_summary.addWidget(self.lbl_summary)
        self.verticalLayout.addLayout(self.layout_summary)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bao Cao Thong Ke Car Care"))
        self.label.setText(_translate("MainWindow", "Tu ngay:"))
        self.label_2.setText(_translate("MainWindow", "Den ngay:"))
        self.btn_doanh_thu.setText(_translate("MainWindow", "Doanh thu va Loi nhuan"))
        self.btn_dich_vu.setText(_translate("MainWindow", "Dich vu ban chay"))
        self.btn_nhan_vien.setText(_translate("MainWindow", "Hieu suat nhan vien"))
        self.lbl_summary.setText(_translate("MainWindow", "Tong doanh thu: 0 VND"))
