# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designer_files/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 780)
        self.main_layout = QtWidgets.QVBoxLayout(Form)
        self.main_layout.setContentsMargins(30, 30, 30, 30)
        self.main_layout.setSpacing(18)
        self.main_layout.setObjectName("main_layout")
        self.lbl_dashboard_title = QtWidgets.QLabel(Form)
        self.lbl_dashboard_title.setObjectName("lbl_dashboard_title")
        self.main_layout.addWidget(self.lbl_dashboard_title)
        self.layout_stat_cards = QtWidgets.QHBoxLayout()
        self.layout_stat_cards.setSpacing(16)
        self.layout_stat_cards.setObjectName("layout_stat_cards")
        self.main_layout.addLayout(self.layout_stat_cards)
        self.lbl_action_title = QtWidgets.QLabel(Form)
        self.lbl_action_title.setObjectName("lbl_action_title")
        self.main_layout.addWidget(self.lbl_action_title)
        self.layout_action_buttons = QtWidgets.QHBoxLayout()
        self.layout_action_buttons.setSpacing(12)
        self.layout_action_buttons.setObjectName("layout_action_buttons")
        self.main_layout.addLayout(self.layout_action_buttons)
        self.lbl_quick_title = QtWidgets.QLabel(Form)
        self.lbl_quick_title.setObjectName("lbl_quick_title")
        self.main_layout.addWidget(self.lbl_quick_title)
        self.layout_quick_charts = QtWidgets.QHBoxLayout()
        self.layout_quick_charts.setSpacing(16)
        self.layout_quick_charts.setObjectName("layout_quick_charts")
        self.main_layout.addLayout(self.layout_quick_charts)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dashboard"))
        self.lbl_dashboard_title.setText(_translate("Form", "TỔNG QUAN HOẠT ĐỘNG"))
        self.lbl_action_title.setText(_translate("Form", "Thao tác nhanh"))
        self.lbl_quick_title.setText(_translate("Form", "Biểu đồ nhanh hôm nay"))
