# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designer_files/qlkhachhang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_search = QtWidgets.QLineEdit(Form)
        self.txt_search.setMinimumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txt_search.setFont(font)
        self.txt_search.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ced4da; /* Viền xám nhạt */\n"
"    border-radius: 5px;        /* Bo tròn 5px */\n"
"    padding: 5px 10px;         /* Khoảng cách chữ bên trong */\n"
"    background-color: white;   /* Nền trắng */\n"
"}\n"
"")
        self.txt_search.setObjectName("txt_search")
        self.horizontalLayout.addWidget(self.txt_search)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 35))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ced4da; /* Viền xám nhạt */\n"
"    border-radius: 5px;        /* Bo tròn 5px */\n"
"    padding: 5px 10px;         /* Khoảng cách chữ bên trong */\n"
"    background-color: white;   /* Nền trắng */\n"
"    color: #333333;            /* Chữ màu xám đen */\n"
"}\n"
"\n"
"/* Tùy chỉnh cái nút mũi tên xổ xuống */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 30px; /* Mở rộng chiều ngang một chút cho dễ bấm */\n"
"}\n"
"\n"
"/* Chèn icon mũi tên màu đen */\n"
"/* Chèn icon mũi tên màu đen */\n"
"QComboBox::down-arrow {\n"
"    image: url(\"C:/Users/LENOVO/OneDrive/Documents/xaydungphanmemquanlydichvuchamsocxeoto/assets/icons/muiten.png\"); \n"
"    width: 12px;  \n"
"    height: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi mũi tên xổ xuống (tùy chọn) */\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px; /* Đẩy mũi tên xuống 1px khi click tạo cảm giác chân thực */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.btn_timkiem = QtWidgets.QPushButton(Form)
        self.btn_timkiem.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_timkiem.setStyleSheet("/* Tùy chỉnh trạng thái bình thường của nút */\n"
"QPushButton {\n"
"    background-color: #007bff; /* Màu xanh dương chủ đạo */\n"
"    color: white;               /* Chữ trắng */\n"
"    border: none;               /* Không viền */\n"
"    border-radius: 5px;         /* Bo tròn góc 5px cho giống ô nhập liệu */\n"
"    padding: 5px 15px;          /* Khoảng cách chữ bên trong */\n"
"    font-weight: bold;          /* Chữ đậm cho dễ nhìn */\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột qua (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #0069d9; /* Màu xanh đậm hơn một chút */\n"
"}\n"
"\n"
"/* Hiệu ứng khi nhấn giữ chuột (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0056b3; /* Màu xanh đậm nhất */\n"
"    padding-left: 17px;        /* Nhích nhẹ chữ sang phải tạo cảm giác nút bị lún xuống */\n"
"    padding-top: 7px;\n"
"}")
        self.btn_timkiem.setObjectName("btn_timkiem")
        self.horizontalLayout.addWidget(self.btn_timkiem)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_themKH = QtWidgets.QPushButton(Form)
        self.btn_themKH.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_themKH.setStyleSheet("QPushButton {\n"
"    background-color: #28a745; /* Nền xanh lá */\n"
"    color: white;              /* Chữ màu trắng */\n"
"    border-radius: 5px;        /* Bo tròn góc 5px */\n"
"    padding: 8px;              /* Khoảng cách từ chữ đến viền */\n"
"    font-weight: bold;         /* In đậm chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838; /* Màu xanh đậm hơn một chút khi đưa chuột qua */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/themKH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_themKH.setIcon(icon)
        self.btn_themKH.setIconSize(QtCore.QSize(23, 23))
        self.btn_themKH.setObjectName("btn_themKH")
        self.horizontalLayout.addWidget(self.btn_themKH)
        self.btn_suaKH = QtWidgets.QPushButton(Form)
        self.btn_suaKH.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_suaKH.setStyleSheet("QPushButton {\n"
"    background-color: #007bff; /* Nền xanh dương */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0069d9; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/suaKH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_suaKH.setIcon(icon1)
        self.btn_suaKH.setIconSize(QtCore.QSize(23, 23))
        self.btn_suaKH.setObjectName("btn_suaKH")
        self.horizontalLayout.addWidget(self.btn_suaKH)
        self.btn_xoaKH = QtWidgets.QPushButton(Form)
        self.btn_xoaKH.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_xoaKH.setStyleSheet("QPushButton {\n"
"    background-color: #dc3545; /* Nền đỏ */\n"
"    color: white; \n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333; /* Đỏ đậm hơn khi đưa chuột qua */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/xoaKH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_xoaKH.setIcon(icon2)
        self.btn_xoaKH.setIconSize(QtCore.QSize(23, 23))
        self.btn_xoaKH.setObjectName("btn_xoaKH")
        self.horizontalLayout.addWidget(self.btn_xoaKH)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbl_customers = QtWidgets.QTableWidget(Form)
        self.tbl_customers.setStyleSheet("/* Khung của toàn bộ bảng */\n"
"QTableWidget {\n"
"    border: 1px solid #ced4da; \n"
"    border-radius: 8px;        /* Bo tròn góc bảng 8px */\n"
"    background-color: white;\n"
"    gridline-color: #e9ecef;   /* Màu của các đường kẻ ô lưới */\n"
"    selection-background-color: #cce5ff; /* Màu nền ô khi bạn click chọn */\n"
"    selection-color: black;    /* Màu chữ khi bạn click chọn */\n"
"}\n"
"\n"
"/* Tùy chỉnh Thanh tiêu đề (Tên các cột: Mã KH, Tên, SĐT...) */\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa; /* Nền xám nhạt cho thanh tiêu đề */\n"
"    border: none;\n"
"    border-bottom: 2px solid #dee2e6; /* Đường kẻ dưới của tiêu đề */\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"    color: #495057;\n"
"}\n"
"\n"
"/* Bo tròn góc trên cùng bên trái và bên phải của Thanh tiêu đề cho khớp với khung bảng */\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 8px;\n"
"}\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 8px;\n"
"}")
        self.tbl_customers.setObjectName("tbl_customers")
        self.tbl_customers.setColumnCount(7)
        self.tbl_customers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_customers.setHorizontalHeaderItem(6, item)
        self.tbl_customers.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tbl_customers)
        self.grp_history = QtWidgets.QGroupBox(Form)
        self.grp_history.setTitle("")
        self.grp_history.setObjectName("grp_history")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grp_history)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.grp_history)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.grp_history)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tbl_history = QtWidgets.QTableWidget(self.grp_history)
        self.tbl_history.setStyleSheet("/* Khung của toàn bộ bảng */\n"
"QTableWidget {\n"
"    border: 1px solid #ced4da; \n"
"    border-radius: 8px;        /* Bo tròn góc bảng 8px */\n"
"    background-color: white;\n"
"    gridline-color: #e9ecef;   /* Màu của các đường kẻ ô lưới */\n"
"    selection-background-color: #cce5ff; /* Màu nền ô khi bạn click chọn */\n"
"    selection-color: black;    /* Màu chữ khi bạn click chọn */\n"
"}\n"
"\n"
"/* Tùy chỉnh Thanh tiêu đề (Tên các cột: Mã KH, Tên, SĐT...) */\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa; /* Nền xám nhạt cho thanh tiêu đề */\n"
"    border: none;\n"
"    border-bottom: 2px solid #dee2e6; /* Đường kẻ dưới của tiêu đề */\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"    color: #495057;\n"
"}\n"
"\n"
"/* Bo tròn góc trên cùng bên trái và bên phải của Thanh tiêu đề cho khớp với khung bảng */\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 8px;\n"
"}\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 8px;\n"
"}")
        self.tbl_history.setObjectName("tbl_history")
        self.tbl_history.setColumnCount(6)
        self.tbl_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_history.setHorizontalHeaderItem(5, item)
        self.tbl_history.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tbl_history)
        self.horizontalLayout_2.addWidget(self.grp_history)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Quản lý khách hàng"))
        self.label.setText(_translate("Form", "Tìm kiếm:"))
        self.txt_search.setPlaceholderText(_translate("Form", "Nhập mã khách hàng/ Tên khách hàng"))
        self.comboBox.setItemText(0, _translate("Form", "Tất cả"))
        self.comboBox.setItemText(1, _translate("Form", "Khách mới"))
        self.comboBox.setItemText(2, _translate("Form", "Khách quay lại"))
        self.comboBox.setItemText(3, _translate("Form", "Khách VIP"))
        self.btn_timkiem.setText(_translate("Form", "Tìm kiếm"))
        self.btn_themKH.setText(_translate("Form", "Thêm khách hàng"))
        self.btn_suaKH.setText(_translate("Form", "Sửa thông tin"))
        self.btn_xoaKH.setText(_translate("Form", "Xóa khách hàng"))
        self.label_4.setText(_translate("Form", "Với tổng chi tiêu > 50 triệu hệ tự động phân loại lên VIP "))
        item = self.tbl_customers.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã khách hàng"))
        item = self.tbl_customers.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên khách hàng"))
        item = self.tbl_customers.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Số điện thoại"))
        item = self.tbl_customers.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Hãng xe"))
        item = self.tbl_customers.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Biển số xe"))
        item = self.tbl_customers.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Phân loại"))
        item = self.tbl_customers.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Tổng chi tiêu"))
        self.label_2.setText(_translate("Form", "Tên:"))
        self.label_3.setText(_translate("Form", "Hạng: "))
        item = self.tbl_history.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ngày dịch vụ"))
        item = self.tbl_history.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hãng xe"))
        item = self.tbl_history.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Biển số xe"))
        item = self.tbl_history.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Dịch vụ đã làm"))
        item = self.tbl_history.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tổng tiền"))
        item = self.tbl_history.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Kỹ thuật viên"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
