# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designer_files/trangchu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 886)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"    color: #0f172a;\n"
"}\n"
"QMainWindow, #centralwidget {\n"
"    background-color: #f3f6fb;\n"
"}\n"
"/* ===== Header ===== */\n"
"#headerFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dbe5f2;\n"
"    border-radius: 14px;\n"
"}\n"
"#logoLabel {\n"
"    background-color: #FFFFFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 28px;\n"
"    border: 1px solid #FFFFFF;\n"
"    font-size: 24px;\n"
"    font-weight: 700;\n"
"}\n"
"#appName {\n"
"    color: #0b1324;\n"
"    font-size: 21px;\n"
"    font-weight: 800;\n"
"}\n"
"#appDesc {\n"
"    color: #5b6b84;\n"
"    font-size: 10.5pt;\n"
"}\n"
"#btnLogin, #btnLogout {\n"
"    min-width: 120px;\n"
"    min-height: 38px;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"    color: #ffffff;\n"
"    font-weight: 700;\n"
"    padding: 6px 14px;\n"
"}\n"
"#btnLogin {\n"
"    background-color: #2563eb;\n"
"}\n"
"#btnLogin:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"#btnLogin:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"#btnLogout {\n"
"    background-color: #ef4444;\n"
"}\n"
"#btnLogout:hover {\n"
"    background-color: #dc2626;\n"
"}\n"
"#btnLogout:pressed {\n"
"    background-color: #b91c1c;\n"
"}\n"
"/* ===== Cards Wrapper ===== */\n"
"#contentWrapper {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"/* ===== Function Cards ===== */\n"
"#card_lichhen,\n"
"#card_pos,\n"
"#card_crm,\n"
"#card_kho,\n"
"#card_nhansu,\n"
"#card_care,\n"
"#card_baocao,\n"
"#card_hethong {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dbe5f2;\n"
"    border-radius: 14px;\n"
"}\n"
"#card_lichhen:hover,\n"
"#card_pos:hover,\n"
"#card_crm:hover,\n"
"#card_kho:hover,\n"
"#card_nhansu:hover,\n"
"#card_care:hover,\n"
"#card_baocao:hover,\n"
"#card_hethong:hover {\n"
"    border: 1px solid #93c5fd;\n"
"    background-color: #fdfefe;\n"
"}\n"
"/* Tieu de card */\n"
"#lblTitleLichHen,\n"
"#lblTitlePOS,\n"
"#lblTitleCRM,\n"
"#lblTitleKho,\n"
"#lblTitleNhanSu,\n"
"#lblTitleCare,\n"
"#lblTitleBaoCao,\n"
"#lblTitleHeThong {\n"
"    color: #0f172a;\n"
"    font-size: 13pt;\n"
"    font-weight: 800;\n"
"}\n"
"/* Mo ta card */\n"
"#lblDescLichHen,\n"
"#lblDescPOS,\n"
"#lblDescCRM,\n"
"#lblDescKho,\n"
"#lblDescNhanSu,\n"
"#lblDescCare,\n"
"#lblDescBaoCao,\n"
"#lblDescHeThong {\n"
"    color: #596980;\n"
"    font-size: 10pt;\n"
"    line-height: 1.25em;\n"
"}\n"
"/* Nut mo chuc nang tren card */\n"
"#btn_lichhen_tiepnhan,\n"
"#btn_banhang_thanhtoan,\n"
"#btn_crm_khachhang,\n"
"#btn_kho_vattu,\n"
"#btn_nhansu_nangsuat,\n"
"#btn_customer_care,\n"
"#btn_baocao_thongke,\n"
"#btn_hethong_caidat {\n"
"    min-height: 36px;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"    background-color: #0ea5e9;\n"
"    color: #ffffff;\n"
"    font-weight: 700;\n"
"    padding: 6px 12px;\n"
"}\n"
"#btn_lichhen_tiepnhan:hover,\n"
"#btn_banhang_thanhtoan:hover,\n"
"#btn_crm_khachhang:hover,\n"
"#btn_kho_vattu:hover,\n"
"#btn_nhansu_nangsuat:hover,\n"
"#btn_customer_care:hover,\n"
"#btn_baocao_thongke:hover,\n"
"#btn_hethong_caidat:hover {\n"
"    background-color: #0284c7;\n"
"}\n"
"#btn_lichhen_tiepnhan:pressed,\n"
"#btn_banhang_thanhtoan:pressed,\n"
"#btn_crm_khachhang:pressed,\n"
"#btn_kho_vattu:pressed,\n"
"#btn_nhansu_nangsuat:pressed,\n"
"#btn_customer_care:pressed,\n"
"#btn_baocao_thongke:pressed,\n"
"#btn_hethong_caidat:pressed {\n"
"    background-color: #0369a1;\n"
"}\n"
"/* ===== Footer ===== */\n"
"#footerText {\n"
"    color: #6b7b93;\n"
"    font-size: 9.5pt;\n"
"    padding-left: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_root = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_root.setContentsMargins(24, 20, 24, 20)
        self.verticalLayout_root.setSpacing(16)
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_header.setContentsMargins(20, 14, 20, 14)
        self.horizontalLayout_header.setSpacing(14)
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.logoLabel = QtWidgets.QLabel(self.headerFrame)
        self.logoLabel.setMinimumSize(QtCore.QSize(56, 56))
        self.logoLabel.setMaximumSize(QtCore.QSize(56, 56))
        self.logoLabel.setText("")
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_header.addWidget(self.logoLabel)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.appName = QtWidgets.QLabel(self.headerFrame)
        self.appName.setText("")
        self.appName.setPixmap(QtGui.QPixmap(":/logo-removebg-preview.png"))
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.verticalLayout_title.addWidget(self.appName)
        self.appDesc = QtWidgets.QLabel(self.headerFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.appDesc.setFont(font)
        self.appDesc.setObjectName("appDesc")
        self.verticalLayout_title.addWidget(self.appDesc)
        self.horizontalLayout_header.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.btnLogout = QtWidgets.QPushButton(self.headerFrame)
        self.btnLogout.setStyleSheet("QPushButton {\n"
"    background-color: #6c757d; /* Màu xám trung tính */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268; /* Xám đậm hơn khi lia chuột */\n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        self.horizontalLayout_header.addWidget(self.btnLogout)
        self.verticalLayout_root.addWidget(self.headerFrame)
        self.contentWrapper = QtWidgets.QFrame(self.centralwidget)
        self.contentWrapper.setObjectName("contentWrapper")
        self.gridLayout_cards = QtWidgets.QGridLayout(self.contentWrapper)
        self.gridLayout_cards.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_cards.setSpacing(12)
        self.gridLayout_cards.setObjectName("gridLayout_cards")
        self.card_lichhen = QtWidgets.QFrame(self.contentWrapper)
        self.card_lichhen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_lichhen.setObjectName("card_lichhen")
        self.verticalLayout_card_lichhen = QtWidgets.QVBoxLayout(self.card_lichhen)
        self.verticalLayout_card_lichhen.setObjectName("verticalLayout_card_lichhen")
        self.lblTitleLichHen = QtWidgets.QLabel(self.card_lichhen)
        self.lblTitleLichHen.setWordWrap(True)
        self.lblTitleLichHen.setObjectName("lblTitleLichHen")
        self.verticalLayout_card_lichhen.addWidget(self.lblTitleLichHen)
        self.lblDescLichHen = QtWidgets.QLabel(self.card_lichhen)
        self.lblDescLichHen.setWordWrap(True)
        self.lblDescLichHen.setObjectName("lblDescLichHen")
        self.verticalLayout_card_lichhen.addWidget(self.lblDescLichHen)
        self.btn_lichhen_tiepnhan = QtWidgets.QPushButton(self.card_lichhen)
        self.btn_lichhen_tiepnhan.setObjectName("btn_lichhen_tiepnhan")
        self.verticalLayout_card_lichhen.addWidget(self.btn_lichhen_tiepnhan)
        self.gridLayout_cards.addWidget(self.card_lichhen, 0, 0, 1, 1)
        self.card_pos = QtWidgets.QFrame(self.contentWrapper)
        self.card_pos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_pos.setObjectName("card_pos")
        self.verticalLayout_card_pos = QtWidgets.QVBoxLayout(self.card_pos)
        self.verticalLayout_card_pos.setObjectName("verticalLayout_card_pos")
        self.lblTitlePOS = QtWidgets.QLabel(self.card_pos)
        self.lblTitlePOS.setWordWrap(True)
        self.lblTitlePOS.setObjectName("lblTitlePOS")
        self.verticalLayout_card_pos.addWidget(self.lblTitlePOS)
        self.lblDescPOS = QtWidgets.QLabel(self.card_pos)
        self.lblDescPOS.setWordWrap(True)
        self.lblDescPOS.setObjectName("lblDescPOS")
        self.verticalLayout_card_pos.addWidget(self.lblDescPOS)
        self.btn_banhang_thanhtoan = QtWidgets.QPushButton(self.card_pos)
        self.btn_banhang_thanhtoan.setObjectName("btn_banhang_thanhtoan")
        self.verticalLayout_card_pos.addWidget(self.btn_banhang_thanhtoan)
        self.gridLayout_cards.addWidget(self.card_pos, 0, 1, 1, 1)
        self.card_crm = QtWidgets.QFrame(self.contentWrapper)
        self.card_crm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_crm.setObjectName("card_crm")
        self.verticalLayout_card_crm = QtWidgets.QVBoxLayout(self.card_crm)
        self.verticalLayout_card_crm.setObjectName("verticalLayout_card_crm")
        self.lblTitleCRM = QtWidgets.QLabel(self.card_crm)
        self.lblTitleCRM.setWordWrap(True)
        self.lblTitleCRM.setObjectName("lblTitleCRM")
        self.verticalLayout_card_crm.addWidget(self.lblTitleCRM)
        self.lblDescCRM = QtWidgets.QLabel(self.card_crm)
        self.lblDescCRM.setWordWrap(True)
        self.lblDescCRM.setObjectName("lblDescCRM")
        self.verticalLayout_card_crm.addWidget(self.lblDescCRM)
        self.btn_crm_khachhang = QtWidgets.QPushButton(self.card_crm)
        self.btn_crm_khachhang.setObjectName("btn_crm_khachhang")
        self.verticalLayout_card_crm.addWidget(self.btn_crm_khachhang)
        self.gridLayout_cards.addWidget(self.card_crm, 1, 0, 1, 1)
        self.card_kho = QtWidgets.QFrame(self.contentWrapper)
        self.card_kho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_kho.setObjectName("card_kho")
        self.verticalLayout_card_kho = QtWidgets.QVBoxLayout(self.card_kho)
        self.verticalLayout_card_kho.setObjectName("verticalLayout_card_kho")
        self.lblTitleKho = QtWidgets.QLabel(self.card_kho)
        self.lblTitleKho.setWordWrap(True)
        self.lblTitleKho.setObjectName("lblTitleKho")
        self.verticalLayout_card_kho.addWidget(self.lblTitleKho)
        self.lblDescKho = QtWidgets.QLabel(self.card_kho)
        self.lblDescKho.setWordWrap(True)
        self.lblDescKho.setObjectName("lblDescKho")
        self.verticalLayout_card_kho.addWidget(self.lblDescKho)
        self.btn_kho_vattu = QtWidgets.QPushButton(self.card_kho)
        self.btn_kho_vattu.setObjectName("btn_kho_vattu")
        self.verticalLayout_card_kho.addWidget(self.btn_kho_vattu)
        self.gridLayout_cards.addWidget(self.card_kho, 1, 1, 1, 1)
        self.card_nhansu = QtWidgets.QFrame(self.contentWrapper)
        self.card_nhansu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_nhansu.setObjectName("card_nhansu")
        self.verticalLayout_card_nhansu = QtWidgets.QVBoxLayout(self.card_nhansu)
        self.verticalLayout_card_nhansu.setObjectName("verticalLayout_card_nhansu")
        self.lblTitleNhanSu = QtWidgets.QLabel(self.card_nhansu)
        self.lblTitleNhanSu.setWordWrap(True)
        self.lblTitleNhanSu.setObjectName("lblTitleNhanSu")
        self.verticalLayout_card_nhansu.addWidget(self.lblTitleNhanSu)
        self.lblDescNhanSu = QtWidgets.QLabel(self.card_nhansu)
        self.lblDescNhanSu.setWordWrap(True)
        self.lblDescNhanSu.setObjectName("lblDescNhanSu")
        self.verticalLayout_card_nhansu.addWidget(self.lblDescNhanSu)
        self.btn_nhansu_nangsuat = QtWidgets.QPushButton(self.card_nhansu)
        self.btn_nhansu_nangsuat.setObjectName("btn_nhansu_nangsuat")
        self.verticalLayout_card_nhansu.addWidget(self.btn_nhansu_nangsuat)
        self.gridLayout_cards.addWidget(self.card_nhansu, 2, 0, 1, 1)
        self.card_care = QtWidgets.QFrame(self.contentWrapper)
        self.card_care.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_care.setObjectName("card_care")
        self.verticalLayout_card_care = QtWidgets.QVBoxLayout(self.card_care)
        self.verticalLayout_card_care.setObjectName("verticalLayout_card_care")
        self.lblTitleCare = QtWidgets.QLabel(self.card_care)
        self.lblTitleCare.setWordWrap(True)
        self.lblTitleCare.setObjectName("lblTitleCare")
        self.verticalLayout_card_care.addWidget(self.lblTitleCare)
        self.lblDescCare = QtWidgets.QLabel(self.card_care)
        self.lblDescCare.setWordWrap(True)
        self.lblDescCare.setObjectName("lblDescCare")
        self.verticalLayout_card_care.addWidget(self.lblDescCare)
        self.btn_customer_care = QtWidgets.QPushButton(self.card_care)
        self.btn_customer_care.setObjectName("btn_customer_care")
        self.verticalLayout_card_care.addWidget(self.btn_customer_care)
        self.gridLayout_cards.addWidget(self.card_care, 2, 1, 1, 1)
        self.card_baocao = QtWidgets.QFrame(self.contentWrapper)
        self.card_baocao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_baocao.setObjectName("card_baocao")
        self.verticalLayout_card_baocao = QtWidgets.QVBoxLayout(self.card_baocao)
        self.verticalLayout_card_baocao.setObjectName("verticalLayout_card_baocao")
        self.lblTitleBaoCao = QtWidgets.QLabel(self.card_baocao)
        self.lblTitleBaoCao.setWordWrap(True)
        self.lblTitleBaoCao.setObjectName("lblTitleBaoCao")
        self.verticalLayout_card_baocao.addWidget(self.lblTitleBaoCao)
        self.lblDescBaoCao = QtWidgets.QLabel(self.card_baocao)
        self.lblDescBaoCao.setWordWrap(True)
        self.lblDescBaoCao.setObjectName("lblDescBaoCao")
        self.verticalLayout_card_baocao.addWidget(self.lblDescBaoCao)
        self.btn_baocao_thongke = QtWidgets.QPushButton(self.card_baocao)
        self.btn_baocao_thongke.setObjectName("btn_baocao_thongke")
        self.verticalLayout_card_baocao.addWidget(self.btn_baocao_thongke)
        self.gridLayout_cards.addWidget(self.card_baocao, 3, 0, 1, 1)
        self.card_hethong = QtWidgets.QFrame(self.contentWrapper)
        self.card_hethong.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_hethong.setObjectName("card_hethong")
        self.verticalLayout_card_hethong = QtWidgets.QVBoxLayout(self.card_hethong)
        self.verticalLayout_card_hethong.setObjectName("verticalLayout_card_hethong")
        self.lblTitleHeThong = QtWidgets.QLabel(self.card_hethong)
        self.lblTitleHeThong.setWordWrap(True)
        self.lblTitleHeThong.setObjectName("lblTitleHeThong")
        self.verticalLayout_card_hethong.addWidget(self.lblTitleHeThong)
        self.lblDescHeThong = QtWidgets.QLabel(self.card_hethong)
        self.lblDescHeThong.setWordWrap(True)
        self.lblDescHeThong.setObjectName("lblDescHeThong")
        self.verticalLayout_card_hethong.addWidget(self.lblDescHeThong)
        self.btn_hethong_caidat = QtWidgets.QPushButton(self.card_hethong)
        self.btn_hethong_caidat.setObjectName("btn_hethong_caidat")
        self.verticalLayout_card_hethong.addWidget(self.btn_hethong_caidat)
        self.gridLayout_cards.addWidget(self.card_hethong, 3, 1, 1, 1)
        self.verticalLayout_root.addWidget(self.contentWrapper)
        self.footerText = QtWidgets.QLabel(self.centralwidget)
        self.footerText.setObjectName("footerText")
        self.verticalLayout_root.addWidget(self.footerText)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trang chủ quản lý"))
        self.appDesc.setText(_translate("MainWindow", "Hệ thống quản lý dịch vụ chăm sóc xe ô tô"))
        self.btnLogout.setText(_translate("MainWindow", "Đăng xuất"))
        self.lblTitleLichHen.setText(_translate("MainWindow", "Quản lý lịch hẹn & Tiếp nhận"))
        self.lblDescLichHen.setText(_translate("MainWindow", "Đặt lịch, check-in, điều phối xe vào dịch vụ"))
        self.btn_lichhen_tiepnhan.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitlePOS.setText(_translate("MainWindow", "Bán hàng & Thanh toán POS"))
        self.lblDescPOS.setText(_translate("MainWindow", "Lập hóa đơn, áp dụng khuyến mãi, in hóa đơn nhanh."))
        self.btn_banhang_thanhtoan.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleCRM.setText(_translate("MainWindow", "Quản lý khách hàng (CRM)"))
        self.lblDescCRM.setText(_translate("MainWindow", "Lưu hồ sơ, lịch sử dịch vụ, chăm sóc theo nhóm khách."))
        self.btn_crm_khachhang.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleKho.setText(_translate("MainWindow", "Quản lý kho & vật tư"))
        self.lblDescKho.setText(_translate("MainWindow", "Nhập / xuất tồn kho, cảnh báo tồn kho thấp, theo dõi danh mục."))
        self.btn_kho_vattu.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleNhanSu.setText(_translate("MainWindow", "Quản lý nhân sự & năng suất"))
        self.lblDescNhanSu.setText(_translate("MainWindow", "Chấm công, chia ca, đo năng suất theo kỹ thuật viên."))
        self.btn_nhansu_nangsuat.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleCare.setText(_translate("MainWindow", "Chăm sóc KH & Marketing (Customer Care)"))
        self.lblDescCare.setText(_translate("MainWindow", "Gửi SMS/Zalo, nhắc bảo dưỡng, chương trình ưu đãi."))
        self.btn_customer_care.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleBaoCao.setText(_translate("MainWindow", "Báo cáo & thống kê"))
        self.lblDescBaoCao.setText(_translate("MainWindow", "Doanh thu, lợi nhuận, tần suất quay lại, KPI"))
        self.btn_baocao_thongke.setText(_translate("MainWindow", "Mở chức năng"))
        self.lblTitleHeThong.setText(_translate("MainWindow", "Quản lý hệ thống & cài đặt"))
        self.lblDescHeThong.setText(_translate("MainWindow", "Phân quyền, sao lưu và khôi phục dữ liệu."))
        self.btn_hethong_caidat.setText(_translate("MainWindow", "Mở chức năng"))
        self.footerText.setText(_translate("MainWindow", "Trang chủ quản lý | Quản lý tổng thể trung tâm chăm sóc xe"))
import img_rc
