# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designer_files/them_sua_voucher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 508)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txt_ma_voucher = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txt_ma_voucher.setFont(font)
        self.txt_ma_voucher.setStyleSheet("QLineEdit, QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #007bff;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #80bdff; /* Đổi viền sang màu xanh khi đang gõ chữ */\n"
"}")
        self.txt_ma_voucher.setObjectName("txt_ma_voucher")
        self.verticalLayout.addWidget(self.txt_ma_voucher)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txt_ten_voucher = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txt_ten_voucher.setFont(font)
        self.txt_ten_voucher.setStyleSheet("QLineEdit, QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #007bff;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #80bdff; /* Đổi viền sang màu xanh khi đang gõ chữ */\n"
"}")
        self.txt_ten_voucher.setText("")
        self.txt_ten_voucher.setObjectName("txt_ten_voucher")
        self.verticalLayout.addWidget(self.txt_ten_voucher)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.cmb_loai_khuyenmai = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cmb_loai_khuyenmai.setFont(font)
        self.cmb_loai_khuyenmai.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ced4da; /* Viền xám nhạt */\n"
"    border-radius: 5px;        /* Bo tròn 5px */\n"
"    padding: 5px 10px;         /* Khoảng cách chữ bên trong */\n"
"    background-color: white;   /* Nền trắng */\n"
"    color: #333333;            /* Chữ màu xám đen */\n"
"}\n"
"\n"
"/* Tùy chỉnh cái nút mũi tên xổ xuống */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 30px; /* Mở rộng chiều ngang một chút cho dễ bấm */\n"
"}\n"
"\n"
"/* Chèn icon mũi tên màu đen */\n"
"/* Chèn icon mũi tên màu đen */\n"
"QComboBox::down-arrow {\n"
"    image: url(\"C:/Users/LENOVO/OneDrive/Documents/xaydungphanmemquanlydichvuchamsocxeoto/assets/icons/muiten.png\"); \n"
"    width: 12px;  \n"
"    height: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi mũi tên xổ xuống (tùy chọn) */\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px; /* Đẩy mũi tên xuống 1px khi click tạo cảm giác chân thực */\n"
"}")
        self.cmb_loai_khuyenmai.setObjectName("cmb_loai_khuyenmai")
        self.cmb_loai_khuyenmai.addItem("")
        self.cmb_loai_khuyenmai.addItem("")
        self.verticalLayout.addWidget(self.cmb_loai_khuyenmai)
        self.txt_gia_tri = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txt_gia_tri.setFont(font)
        self.txt_gia_tri.setStyleSheet("QLineEdit, QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #007bff;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #80bdff; /* Đổi viền sang màu xanh khi đang gõ chữ */\n"
"}")
        self.txt_gia_tri.setObjectName("txt_gia_tri")
        self.verticalLayout.addWidget(self.txt_gia_tri)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.dat_ngay_bd = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.dat_ngay_bd.setFont(font)
        self.dat_ngay_bd.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #ced4da; /* Viền xám nhạt */\n"
"    border-radius: 5px;        /* Bo tròn 5px */\n"
"    padding: 5px 10px;         /* Khoảng cách chữ bên trong */\n"
"    background-color: white;   /* Nền trắng */\n"
"    color: #333333;            /* Chữ màu xám đen */\n"
"}\n"
"")
        self.dat_ngay_bd.setObjectName("dat_ngay_bd")
        self.verticalLayout.addWidget(self.dat_ngay_bd)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.dat_ngay_kt = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.dat_ngay_kt.setFont(font)
        self.dat_ngay_kt.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #ced4da; /* Viền xám nhạt */\n"
"    border-radius: 5px;        /* Bo tròn 5px */\n"
"    padding: 5px 10px;         /* Khoảng cách chữ bên trong */\n"
"    background-color: white;   /* Nền trắng */\n"
"    color: #333333;            /* Chữ màu xám đen */\n"
"}\n"
"")
        self.dat_ngay_kt.setObjectName("dat_ngay_kt")
        self.verticalLayout.addWidget(self.dat_ngay_kt)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.txt_mota_voucher = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txt_mota_voucher.setFont(font)
        self.txt_mota_voucher.setStyleSheet("QLineEdit, QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #007bff;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #80bdff; /* Đổi viền sang màu xanh khi đang gõ chữ */\n"
"}")
        self.txt_mota_voucher.setObjectName("txt_mota_voucher")
        self.verticalLayout.addWidget(self.txt_mota_voucher)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_luu_voucher = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_luu_voucher.setFont(font)
        self.btn_luu_voucher.setStyleSheet("QPushButton {\n"
"    background-color: #007bff; /* Màu xanh dương hiện đại */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 15px;         /* Cho nút dài ra một chút */\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Xanh đậm hơn khi lia chuột */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/luu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_luu_voucher.setIcon(icon)
        self.btn_luu_voucher.setObjectName("btn_luu_voucher")
        self.horizontalLayout.addWidget(self.btn_luu_voucher)
        self.btn_huy_bo = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_huy_bo.setFont(font)
        self.btn_huy_bo.setStyleSheet("QPushButton {\n"
"    background-color: #6c757d; /* Màu xám trung tính */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268; /* Xám đậm hơn khi lia chuột */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/huy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_huy_bo.setIcon(icon1)
        self.btn_huy_bo.setObjectName("btn_huy_bo")
        self.horizontalLayout.addWidget(self.btn_huy_bo)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thêm/ Sửa Voucher"))
        self.label.setText(_translate("Form", "Mã Voucher:"))
        self.txt_ma_voucher.setPlaceholderText(_translate("Form", "Ví dụ: GIAM50K"))
        self.label_2.setText(_translate("Form", "Tên chương trình:"))
        self.txt_ten_voucher.setPlaceholderText(_translate("Form", "Ví dụ: Khuyến mãi Hè 2024"))
        self.label_3.setText(_translate("Form", "Loại giảm giá:"))
        self.cmb_loai_khuyenmai.setItemText(0, _translate("Form", "Giảm theo %"))
        self.cmb_loai_khuyenmai.setItemText(1, _translate("Form", "Giảm theo số tiền (VNĐ)"))
        self.txt_gia_tri.setPlaceholderText(_translate("Form", "Nhập số tiền VNĐ hoặc số %"))
        self.label_4.setText(_translate("Form", "Ngày bắt đầu:"))
        self.label_5.setText(_translate("Form", "Ngày kết thúc:"))
        self.label_6.setText(_translate("Form", "Ghi chú:"))
        self.btn_luu_voucher.setText(_translate("Form", "Lưu"))
        self.btn_huy_bo.setText(_translate("Form", "Hủy"))
import resources_rc
